# Generated by Django 4.1.7 on 2023-03-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pranthi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='sss',
        ),
    ]
