# Generated by Django 4.1.7 on 2023-03-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pranthi_app', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user_table',
        ),
    ]
