# Generated by Django 4.1.7 on 2023-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pranthi_app', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
