# Generated by Django 4.1.7 on 2023-03-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pranthi_app', '0004_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid_field',
            field=models.UUIDField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
